FROM python:3.10.12-bullseye

RUN apt-get update --fix-missing
# RUN apt-get install -y python3 
# RUN apt-get install -y python3-pip 
# RUN apt-get install -y python3.10-venv
RUN apt-get install -y git